name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-nix:

    runs-on: ${{ matrix.os }} 

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        arch: ["86", "86-64"]

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make ARCH=${{ matrix.arch }}
    - name: test
      run: bin/86-64/test
    - name: stress
      run: bin/86-64/stress

